version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - run: echo "nothing to do"

  publish-gh-pages:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: install awscli
          command: pip3 install awscli
      - run:
          name: "Deploy to CloudFront"
          command: |
            npm run-script build
            aws s3 sync ./public s3://holepunch.io

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish-gh-pages:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^punch_version_\d+\.\d+\.\d+$/
