version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - run: echo "nothing to do"

  publish-gh-pages:
    docker:
      - image: circleci/node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: "Publish gh-pages"
          command: |
            git config --global user.email "<email>"
            git config --global user.name "Holepunch-Site Deployment Bot"
            npm install
            npm run deploy

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - publish-gh-pages:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^punch_version_\d+\.\d+\.\d+$/
